### ISSUE TITLE
Please white list 0bda:a811 Realtek

### ISSUE THREAD

**Issue by Sydnnix** [RinCat/RTL88x2BU-Linux-Driver#105]
Hi RinCat,

It is a generic non-branded cheap USB dongle that is selling at various ebay stores. The name can be anything similar to *5dBi Antenna 802.11ac AC600 USB WiFi Wireless Adapter Dongle WPS 5GHz Dual Band".
Could you add it to the white list?

Bus 001 Device 011: ID 0bda:a811 Realtek Semiconductor Corp. RTL8811AU 802.11a/b/g/n/ac WLAN Adapter

Thanks a lot!

Sun

**Comment by RinCat** [comment]
@Sydnnix Hi, that's RTL8811AU chip, should not use this driver.

**Comment by Sydnnix** [comment]
> @Sydnnix Hi, that's RTL8811AU chip, should not use this driver.

thanks @RinCat ! Sorry for the wrong request.
