### ISSUE TITLE
Monitor mode and "packet injection" compatibility

### ISSUE THREAD

**Issue by wedrano99** [RinCat/RTL88x2BU-Linux-Driver#111]
hey! this is not a issue, but a need some help :) 
how can i activate the monitor mode on this drive? and you guys knows if this type of adapters is compatible with "packet injection"?
thanks for u attention :)

**Comment by morrownr** [comment]
@RinCat 

I recently updated my repo to a new version of this driver. I wasn't planning on supporting monitor mode but it works well. Here is the repo:

https://github.com/morrownr/88x2bu-20210702

Be glad to drop a copy of clean source here if you prefer.

Regards,

Nick

**Comment by RinCat** [comment]
@wedrano99 This one support monitor mode and packet injection. You need to follow airmon-ng docs, there is nothing you need to set in the driver.

https://github.com/RinCat/RTL88x2BU-Linux-Driver/pull/51

**Comment by RinCat** [comment]
@morrownr If you can tell me where you found the new driver would be better.

**Comment by morrownr** [comment]
Edimax

**Comment by RinCat** [comment]
That seems a huge version bump.

**Comment by wedrano99** [comment]
Thanks guys, you are amazing! :)
