### ISSUE TITLE
Feature: Add instructions to build locally

### ISSUE THREAD

**Issue by dragon212c** [RinCat/RTL88x2BU-Linux-Driver#12]
I think there is a time when you can't use the internet and the only choice is building the drivers manually, my simple request is add more information about how to build the driver in the readme text file, this would be very helpful for people who don't know what to do when presented with a driver like this.
Thank you.

**Comment by RinCat** [comment]
Hi, I just updated some info, anything else need to be add?

**Comment by dragon212c** [comment]
@RinCat No thats fantastic I didn't know it was as simple as that, compared to other drivers this was very easy to understand, and thank you for doing it quick!
