### ISSUE TITLE
New version 5.6.1.6 available

### ISSUE THREAD

**Issue by esemeniuc** [RinCat/RTL88x2BU-Linux-Driver#13]
This supports Linux 5.3 natively

Download http://www.cudytech.com/wu1200_software_download

Version string:
RTL88x2BU_WiFi_linux_v5.6.1.6_35492.20191025_COEX20180928-6a6a

**Comment by RinCat** [comment]
Thanks, will update soom

**Comment by RinCat** [comment]
Done
