### ISSUE TITLE
Please add DLink DWA-183 usb device id 

### ISSUE THREAD

**Issue by kmkorym** [RinCat/RTL88x2BU-Linux-Driver#136]
I added the device usb id (2001:331f)  after download the source code.
I built it and install, it works.
![Screenshot_20220506_161136](https://user-images.githubusercontent.com/89539621/167093338-137d42f8-216c-4e58-acdc-9fe99bada16e.png)

System info:
![Screenshot_20220506_161704](https://user-images.githubusercontent.com/89539621/167094231-e518bddc-93cb-4d90-9a87-caaa1a5fd04f.png)

Thanks!

**Comment by RinCat** [comment]
Thanks for the report, added https://github.com/RinCat/RTL88x2BU-Linux-Driver/commit/a3073c7a25d0201ae58bd2aabda37ac2490c6e33 .
