### ISSUE TITLE
TPlink Archer T4U v3

### ISSUE THREAD

**Issue by heri16** [RinCat/RTL88x2BU-Linux-Driver#15]
Please help to whitelist:

https://www.tp-link.com/us/support/download/archer-t4u/

HW version 3

```
[user@user-pc ~]$ lsusb
Bus 003 Device 003: ID 03eb:ff02 Atmel Corp. WootingTwo
Bus 001 Device 002: ID 2357:0115 TP-Link 802.11ac NIC
```

**Comment by RinCat** [comment]
Archer T4U v3 already in the whitelist.
Try load module manually?
