### ISSUE TITLE
Build failed on 5.19.2-arch1-1

### ISSUE THREAD

**Issue by YukiSou** [RinCat/RTL88x2BU-Linux-Driver#150]
make[2]: *** [scripts/Makefile.build:249: /var/lib/dkms/rtl88x2bu/git/build/os_dep/linux/ioctl_cfg80211.o] Error 1

[make.log](https://github.com/RinCat/RTL88x2BU-Linux-Driver/files/9375175/make.log)

**Comment by RinCat** [comment]
Fixed in https://github.com/RinCat/RTL88x2BU-Linux-Driver/commit/3d25a90142c38c8401f02c15a34b6e96952ceb0e
