### ISSUE TITLE
[Question] Something about USB 3.0

### ISSUE THREAD

**Issue by RaptaG** [RinCat/RTL88x2BU-Linux-Driver#154]
Hi!

I got my WiFi adapter (`RTL88x2bu`) connected to a USB 3.0 port and it works just fine.
If I follow [these instructions](https://github.com/RinCat/RTL88x2BU-Linux-Driver#usb-30-support) from the README, will they improve anything?

**Comment by RinCat** [comment]
Hi. If you are using it with 5Ghz, enable USB 3.0 may increase your network speed.

**Comment by RaptaG** [comment]
> Hi. If you are using it with 5Ghz, enable USB 3.0 may increase your network speed.

Ok, thanks!

**Comment by RaptaG** [comment]
Btw, if the restart loop bug happens, how do I remove the parameter are reload the driver. Also will this reset with kernel updates?

Sorry if I bother you @RinCat

**Comment by RinCat** [comment]
The restart loop is this kernel module, not your system. So it will keep retrying to connect your adapter, but will not damage anything. You can simply unload the driver by using `modprobe -r 88x2bu`. 
Also it has nothing to do with kernel updates.

**Comment by RaptaG** [comment]
My connection seems to be a bit instable now..

**Comment by RinCat** [comment]
Then you can just disable it. Maybe power supply not enough or higher speed causes packets loss.

**Comment by RaptaG** [comment]
> Then you can just disable it. Maybe power supply not enough or higher speed causes packets loss.

By forcing USB 2.0?

**Comment by RinCat** [comment]
By remove `rtw_switch_usb_mode=1`. It usually use 2.0 by default.

**Comment by RaptaG** [comment]
> By remove `rtw_switch_usb_mode=1`. It usually use 2.0 by default.

From where?

**Comment by RinCat** [comment]
From where you added it. If you use README, it is in `/etc/modprobe.d/99-RTL88x2BU.conf`.
