### ISSUE TITLE
[Error] Missing kernel headers for module

### ISSUE THREAD

**Issue by hood** [RinCat/RTL88x2BU-Linux-Driver#155]
Installing this module in Arch (`5.19.4-arch1-1`) through yay (so tapping from the AUR) I'm getting the following error:

```
==> dkms install --no-depmod rtl88x2bu/5.13.1.r170.624f131 -k 5.19.4-arch1-1
==> depmod 5.19.4-arch1-1
==> ERROR: Missing 5.9.8-arch1-1 kernel headers for module rtl88x2bu/5.13.1.r170.624f131
```

Any ideas on how to proceed?

**Comment by RinCat** [comment]
Hi, your module installed successful for the kernel `5.19.4-arch1-1`.
The error is happened on your old kernel `5.9.8-arch1-1`, which I think you just need to remove the old one.

**Comment by hood** [comment]
Aw, right, that makes sense! Sorry for the useless issue, thanks!
