### ISSUE TITLE
Fails to build on kernel 5.6.8 - Fedora 31

### ISSUE THREAD

**Issue by silviucc** [RinCat/RTL88x2BU-Linux-Driver#17]
Hi,

It worked with the 5.5 series of kernels.

[compile_error.txt](https://github.com/RinCat/RTL88x2BU-Linux-Driver/files/4568274/compile_error.txt)

**Comment by RinCat** [comment]
This has been fixed, please use git version.

**Comment by silviucc** [comment]
Yes. It seems I had an older version. Latest from git worked fine.

Thanks.
