### ISSUE TITLE
HOW EXACTLY TO COMMIT IN FOREIGN REPOSITORY

### ISSUE THREAD

**Issue by tangorishi** [RinCat/RTL88x2BU-Linux-Driver#172]
i am totally a beginner at github can anyone let me know how can i make my first commit in repositories other than my own

**Comment by RinCat** [comment]
You can't make commit in repositories that you are not part of members.
Create pull requests instead. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by tangorishi** [comment]
got it thanks for helping out
