### ISSUE TITLE
TPLink T3U Archer

### ISSUE THREAD

**Issue by Nic69Han** [RinCat/RTL88x2BU-Linux-Driver#18]
Hi,
Thanks for this driver which works perfectly with a 5.0.0-48 kernel but impossible with a 5.3 kernel.
Is there a solution?
I tried to load it manually and also with dkms.

The compilation goes well, but when loading with modprobe, there is no life.
I restarted the system and the usb wlan key is not recognized.

Thanks

nic@nic69:~$ lsusb
Bus 002 Device 006: ID 2357:012d

**Comment by RinCat** [comment]
Any log? did dmesg shows any error?

**Comment by Nic69Han** [comment]
Hi,
it works fine with Ubuntu 20.04 (5.4.0.33 generic Kernel)
