### ISSUE TITLE
Realtek AC-1200 Mbps not working ubuntu 16.04

### ISSUE THREAD

**Issue by erotavlasme** [RinCat/RTL88x2BU-Linux-Driver#21]
Hi,
I have a wifi adapter realtek AC-1200 Mbps dual band. It works well on lubuntu 20.04 LTS 64 bit with [this driver](https://github.com/cilynx/rtl88x2bu) while I'm not able to use it under ubuntu 16.04 LTS 64 bit so I tried with your driver. However, it does not work. Finally, I do not have any further information about brand and web site.
```
lsusb
Bus 003 Device 006: ID 0bda:b812 Realtek Semiconductor Corp.
```
Thank

**Comment by RinCat** [comment]
0bda:b812 is in the whitelist, is there any dmesg output?

**Comment by erotavlasme** [comment]
Hi,
it is my fault. I tried with a clean VM and it worked, so there is some issue with my system.
