### ISSUE TITLE
Which driver?

### ISSUE THREAD

**Issue by djzort** [RinCat/RTL88x2BU-Linux-Driver#22]
It seems there are similar efforts on this driver at https://github.com/cilynx/rtl88x2bu
Is there any relationship between the two efforts? Which is "best"?

**Comment by RinCat** [comment]
Both are based on Realtek official open source driver. The version is also same (you need change branch to 5.6.1.6 in cilynx).
While cilynx version do have some extra patches, I prefer keep the original as long as it not broken.
Both should works fine in most cases.

**Comment by djzort** [comment]
Ok wow thanks for the fast response. Can you comment on this? https://github.com/EntropicEffect/rtl8822bu

**Comment by RinCat** [comment]
That's 2 years old 5.3.1 version.

**Comment by Polve** [comment]
Is there any possibility to push this upstream?

**Comment by RinCat** [comment]
@Polve which upstream? Realtek? They only release the final source code. There is no repo outside the company people can access.

**Comment by Polve** [comment]
I was thinking about the linux kernel: there are many realtek drivers, why not this one?

**Comment by RinCat** [comment]
@Polve Those drivers were not suppose to put in kernel at first place, thus the code design and quality do not meet the kernel requirements. They may need rewrite a lot of code to do so. 
https://www.phoronix.com/scan.php?page=news_item&px=Realtek-RTW88-WiFi-Linux-Driver

**Comment by Polve** [comment]
Thanks @RinCat  for the prompt reply!
