### ISSUE TITLE
Zorin OS 17.1 Core (Archer T2U Plus [RTL8821AU]) Cannot See Any Available Connections 

### ISSUE THREAD

**Issue by Outspending** [RinCat/RTL88x2BU-Linux-Driver#233]
So i did the installation as normal, and Ubuntu does detect the driver because before it said there's no available adapters when opening the wifi menu, now it tries to find connections although none appear.

Here's my `dkms status`:
![image](https://github.com/RinCat/RTL88x2BU-Linux-Driver/assets/92287257/e0a469ff-e710-4e17-bc42-8226832f000b)

Also my `lsusb`:
![image](https://github.com/RinCat/RTL88x2BU-Linux-Driver/assets/92287257/3d744c8d-1e02-4d3d-bb55-e0bc685fa722)

The Wifi Panel:
![image](https://github.com/RinCat/RTL88x2BU-Linux-Driver/assets/92287257/0ff31e11-a63b-4ae5-9c4c-34f27131f69d)

**Comment by RinCat** [comment]
Hi, this driver only works for RTL88x2**B**U. You will need to find AU version for your T2U Plus. They are different chips.

**Comment by Outspending** [comment]
OH that's my bad, i swear i've used this driver before with this chip. Totally my bad :skull: thank you!
