### ISSUE TITLE
compilation error on the kernel 6.9.2: `cfg80211_ch_switch_notify`

### ISSUE THREAD

**Issue by beroal** [RinCat/RTL88x2BU-Linux-Driver#234]
Hi. I've got a compilation error similar to [“build errors on 6.9.0 rc0”](https://github.com/morrownr/8814au/issues/128). Something about too many arguments to functions `cfg80211_ch_switch_started_notify` and `cfg80211_ch_switch_notify`. See [make.log](https://github.com/RinCat/RTL88x2BU-Linux-Driver/files/15474616/make.log).

**Comment by RinCat** [comment]
Hi, please update you local driver,  this one fixed 2 months ago.

**Comment by beroal** [comment]
I'm sorry. `rua` doesn't offer to update a Git package when its repository is updated.
