### ISSUE TITLE
Is 5Ghz ac supported?

### ISSUE THREAD

**Issue by veloc1ty** [RinCat/RTL88x2BU-Linux-Driver#24]
Hi,

I was just wondering wether this driver supports 5Ghz WiFi - I have installed it via AUR and I do not see any of my 5 GHz networks - 2.4 works fine though.

I'm on Arch Linux 5.7 latest, using a netgear a6150 usb.
Also tried it with LTS kernel and got the same result.

Thanks and kind regards,
Alex

**Comment by RinCat** [comment]
It does support 802.11ac @ 5GHz.

**Comment by veloc1ty** [comment]
Thank you, I guess I need to fiddle around a bit then.
