### ISSUE TITLE
CPU WARN on Ubuntu 20.04 (Kernel 5.4.0-42)

### ISSUE THREAD

**Issue by ryan-esty** [RinCat/RTL88x2BU-Linux-Driver#25]
I'm seeing a kernel exception and I'm not sure if I fixed it locally correctly. The trace is on paste bin:
https://pastebin.com/XdtD8hU9

After zeroing out chdef->edmg in rtw_chbw_to_cfg80211_chan_def the exception went away. Looks like others are looking at edmg to see if it is valid and if not throwing a CPU WARN.

**Comment by RinCat** [comment]
Fixed, try the new one. https://github.com/RinCat/RTL88x2BU-Linux-Driver/commit/314b662331971b10eb484fbcedb06bf5abfcb211

**Comment by ryan-esty** [comment]
Thanks that works.
