### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by vav4eg** [RinCat/RTL88x2BU-Linux-Driver#3]
Hi, when I install the driver, the following error appears. But the driver is assembled and installed. How critical is it?

/home/....../RTL88x2BU_1/os_dep/linux/ioctl_mp.c:308:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~

**Comment by RinCat** [comment]
Seems your gcc still use outdated ISO C90.
Try build with 
`CFLAGS="-std=c11" make`

**Comment by vav4eg** [comment]
I'm sorry, I'm new to this system, tell me, and how to upgrade?) - gcc still use outdated ISO C90


**Conclusion on the advice (if I did everything correctly)**

root@ubuntu:/home/vav4eg/RTL88x2BU_1# CFLAGS="-std=c11" make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.0.10-050010-generic/build M=/home/vav4eg/RTL88x2BU_1  modules
make[1]: вход в каталог «/usr/src/linux-headers-5.0.10-050010-generic»
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_cmd.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_security.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_debug.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_io.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_ioctl_query.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_ioctl_set.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_ieee80211.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_mlme.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_mlme_ext.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_mi.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_wlan_util.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_vht.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_pwrctrl.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_rf.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_recv.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_sta_mgt.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_ap.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/mesh/rtw_mesh.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/mesh/rtw_mesh_pathtbl.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/mesh/rtw_mesh_hwmp.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_xmit.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_p2p.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_rson.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_tdls.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_br_ext.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_iol.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_sreset.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_btcoex_wifionly.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_btcoex.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_beamforming.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_odm.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_rm.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_rm_fsm.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/efuse/rtw_efuse.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/osdep_service.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/os_intfs.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/usb_intf.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/usb_ops_linux.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_linux.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/xmit_linux.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/mlme_linux.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/recv_linux.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_cfg80211.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/rtw_cfgvendor.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/wifi_regd.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/rtw_android.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/rtw_proc.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/rtw_rhashtable.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.o
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_write_reg’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:46:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_read_reg’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:132:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_write_rf’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:266:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_read_rf’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:308:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_rate’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:417:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_channel’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:467:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ch_offset’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:496:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_bandwidth’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:524:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_txpower_index’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:556:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length + 1];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_txpower’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:585:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ant_tx’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:623:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_ant_rx’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:671:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_disable_bt_coexist’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:851:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8 input[wrqu->data.length + 1];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_arx’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:889:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_pwrtrk’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1068:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_psd’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1106:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length + 1];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_dump’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1221:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_phypara’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1247:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_SetRFPath’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1273:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_switch_rf_path’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1322:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->length];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_QueryDrv’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1371:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  char input[wrqu->data.length];
  ^~~~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_PwrCtlDM’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:1400:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->length];
  ^~
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c: In function ‘rtw_mp_hwtx’:
/home/vav4eg/RTL88x2BU_1/os_dep/linux/ioctl_mp.c:2050:2: warning: ISO C90 forbids variable length array ‘input’ [-Wvla]
  u8  input[wrqu->data.length];
  ^~
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_intf.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_com.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_com_phycfg.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_phy.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_dm.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_dm_acs.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_btcoex_wifionly.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_btcoex.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_mp.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_mcc.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_hci/hal_usb.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/led/hal_led.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/led/hal_usb_led.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/hal_halmac.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/rtl8822b_halinit.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/rtl8822b_mac.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/rtl8822b_cmd.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/rtl8822b_phy.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/rtl8822b_ops.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/hal8822b_fw.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/usb/rtl8822bu_halinit.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/usb/rtl8822bu_halmac.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/usb/rtl8822bu_io.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/usb/rtl8822bu_xmit.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/usb/rtl8822bu_recv.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/usb/rtl8822bu_led.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/rtl8822b/usb/rtl8822bu_ops.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/efuse/rtl8822b/HalEfuseMask8822B_USB.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_api.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_bb_rf_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_cfg_wmac_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_common_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_efuse_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_flash_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_fw_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_gpio_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_init_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_mimo_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_pcie_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_sdio_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_usb_88xx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_cfg_wmac_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_common_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_gpio_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_init_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_pcie_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_phy_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_pwr_seq_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_sdio_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/halmac/halmac_88xx/halmac_8822b/halmac_usb_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_debug.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_antdiv.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_soml.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_smt_ant.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_antdect.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_interface.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_phystatus.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_hwconfig.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_dig.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_pathdiv.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_rainfo.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_dynamictxpower.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_adaptivity.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_cfotracking.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_noisemonitor.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_beamforming.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_dfs.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/txbf/halcomtxbf.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/txbf/haltxbfinterface.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/txbf/phydm_hal_txbf_api.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_adc_sampling.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_ccx.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_psd.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_primary_cca.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_cck_pd.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_rssi_monitor.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_auto_dbg.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_math_lib.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_api.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/phydm_pow_train.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/halrf/halrf.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/halrf/halphyrf_ce.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/halrf/halrf_powertracking_ce.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/halrf/halrf_powertracking.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/halrf/halrf_kfree.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/rtl8822b/halhwimg8822b_bb.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/rtl8822b/halhwimg8822b_mac.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/rtl8822b/halhwimg8822b_rf.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/halrf/rtl8822b/halrf_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/rtl8822b/phydm_hal_api8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/halrf/rtl8822b/halrf_iqk_8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/rtl8822b/phydm_regconfig8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/rtl8822b/phydm_rtl8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/phydm/txbf/haltxbf8822b.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/btc/halbtc8822bwifionly.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/btc/halbtc8822b1ant.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/hal/btc/halbtc8822b2ant.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/platform/platform_ops.o
  CC [M]  /home/vav4eg/RTL88x2BU_1/core/rtw_mp.o
  LD [M]  /home/vav4eg/RTL88x2BU_1/88x2bu.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/vav4eg/RTL88x2BU_1/88x2bu.mod.o
  LD [M]  /home/vav4eg/RTL88x2BU_1/88x2bu.ko
make[1]: выход из каталога «/usr/src/linux-headers-5.0.10-050010-generic»

**Comment by RinCat** [comment]
Which system you are using? and version?

**Comment by vav4eg** [comment]
Ubuntu 18.04.2 LTS
Linux ubuntu 5.0.10-050010-generic #201904270832 SMP Sat Apr 27 08:34:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
5.0.10-050010-generic

**Comment by vav4eg** [comment]
Linux version 5.0.10-050010-generic (kernel@kathleen) (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)) #201904270832 SMP Sat Apr 27 08:34:43 UTC 2019

**Comment by RinCat** [comment]
Seems the warning can be ignored.

**Comment by vav4eg** [comment]
Thank you very much for the answer and advice :-)

**Comment by RinCat** [comment]
Some of code using newer C standard and the old C not support, but gcc seems can deal with it. So no affect.

**Comment by vav4eg** [comment]
Thank you very much for your code, I have been trying various versions for a very long time, but only your code works for me

**Comment by RinCat** [comment]
I spent some time fixed all warnings in the new version. At least no longer have any warning for me in gcc 9.3 and clang 10.
