### ISSUE TITLE
TRENDnet TEW-808UBM Micro AC1200 Wireless USB Adapter 20f4:808a

### ISSUE THREAD

**Issue by dandar** [RinCat/RTL88x2BU-Linux-Driver#30]
For the device
TRENDnet TEW-808UBM Micro AC1200 Wireless USB Adapter
20f4:808a,  see notes https://github.com/cilynx/rtl88x2bu/issues/73

Please add support to this driver for the above device, thank you.

**Comment by RinCat** [comment]
https://github.com/RinCat/RTL88x2BU-Linux-Driver/commit/220508d67c7cb518cecdecea469a1c360c5a904e
Done
