### ISSUE TITLE
TP-LINK T3U plus

### ISSUE THREAD

**Issue by semsamboon** [RinCat/RTL88x2BU-Linux-Driver#33]
I have both kali machine and virtual machine but when i connected my wireless adpater it shows green led but when I tried ipconfig, iwconfig there is no wlan0 showing.

**Comment by semsamboon** [comment]
Updated:
It works perfectly. Thank you! It has been a week trying to get my wireless adapter to work.

**Comment by JeevanMalla** [comment]
Could you please help me
