### ISSUE TITLE
Issue on line 45

### ISSUE THREAD

**Issue by rempairamore** [RinCat/RTL88x2BU-Linux-Driver#47]
make command works only if I delete line 45.

Please verify.

**Comment by RinCat** [comment]
Hi, which file line 45?

**Comment by rempairamore** [comment]
./core/rtw_debug.c

**Comment by RinCat** [comment]
Your compiler does not support `__DATE__` and/or `__TIME__`?  This is rare.

**Comment by rempairamore** [comment]
Installed on 2020.3-Kali Linux 64-Bit (Live)
https://cdimage.kali.org/kali-2020.3/kali-linux-2020.3-live-amd64.iso

**Comment by Sascha324** [comment]
you have to install bc before. It's not included in kali.

download:
sudo apt-get download bc

hope this helps

**Comment by rempairamore** [comment]
Thanks Sascha324
It works great!
