### ISSUE TITLE
Load Drivers without Rebooting (Live System)

### ISSUE THREAD

**Issue by Sascha324** [RinCat/RTL88x2BU-Linux-Driver#48]
Hi,

is there a way to load the drivers without rebooting the Computer after installing them?
(For Example with a Live-System from USB-Drive)

Thanks
Sascha

**Comment by RinCat** [comment]
Hi, just run `modprobe 88x2bu` as root

**Comment by Sascha324** [comment]
> Hi, just run `modprobe 88x2bu` as root

Thanks, worked.
