### ISSUE TITLE
Support for Comfast AC dongle

### ISSUE THREAD

**Issue by unmesh59** [RinCat/RTL88x2BU-Linux-Driver#52]
I looked at the usb_intf.c file and you have both 0bda:b812 and 0bda:c811 listed but the driver only works for the first of these. Is there a flag I should have used to enable support of the second device?

Thanks

**Comment by RinCat** [comment]
0bda:c811 is 8811CU, not BU.

**Comment by unmesh59** [comment]
Oops! My bad for only looking at the #defines
