### ISSUE TITLE
Support for Kernel >= 5.12, GRO_DROP no longer returned

### ISSUE THREAD

**Issue by stahlbauer** [RinCat/RTL88x2BU-Linux-Driver#81]
Module does not yet compile for kernel 5.12.

Routine `rtw_napi_gro_receive()` can no longer return `GRO_DROP`. Set the directive `CONFIG_RTW_GRO` based on the kernel version?

See https://github.com/lwfinger/rtl8723du/commit/9690f34fc2603d04b53432df4e3d6c282f3d1ca6

**Comment by RinCat** [comment]
Fixed in https://github.com/RinCat/RTL88x2BU-Linux-Driver/commit/657b7cfde9958e273febdeaeac579902e407f577
