### ISSUE TITLE
Problem BrosTrend AC1200 AC3L V2 - Archlinux

### ISSUE THREAD

**Issue by Froggy232** [RinCat/RTL88x2BU-Linux-Driver#86]
Hi,

I just bought a BrosTrend AC1200 AC3L V2, it uses a RealTek RTL88x2bu chipset. The key is detected by lsusb, but doesn't appear anywhere in NetworkManager.
I have try to install the package rtl88x2bu-dkms-git (https://aur.archlinux.org/packages/rtl88x2bu-dkms-git/) but it doesn't change anything.
I, of course, use the latest arch stable kernel.

Does someone have an idea? I'm a complete noob when it come to WiFi.

Thanks you a lot!

**Comment by Froggy232** [comment]
The problem came from lockdown mode, I had totally forgot that

**Comment by spexgaelen** [comment]
Can you offer any clues about how to resolve the problem originating with lockdown?
I have the same device and the module seemed to install just fine, but mine similarly is not appear in NetworkManager.
