### ISSUE TITLE
set_wiphy_netns is missing.

### ISSUE THREAD

**Issue by yananet** [RinCat/RTL88x2BU-Linux-Driver#90]
Hello.

The driver works fine, but `set_wiphy_netns` is missing.
```
$ iw list
	Supported commands:
	...
		 * set_wiphy_netns
	...
```
I have one rtl8812 Wi-Fi, I could see this with with https://github.com/cilynx/rtl88x2bu,
however, in this driver, monitor mode and MIMO are missing...

Can you please let me know how I can enable this?

**Comment by RinCat** [comment]
NS is not support in the official driver, I need add a patch.

**Comment by RinCat** [comment]
Try the latest version.

**Comment by yananet** [comment]
What do you mean by the latest version?

FYI,
I also issued this for 8814au as well...
https://github.com/morrownr/8814au/issues/23

**Comment by RinCat** [comment]
git pull or download this driver again and install.

**Comment by yananet** [comment]
It works! Thank you!
