### ISSUE TITLE
Whitelist Issue (?)

### ISSUE THREAD

**Issue by SherlockZeus** [RinCat/RTL88x2BU-Linux-Driver#91]
Hi, I'm wondering if I have a whitelist issue, may not. I had a variant of the 8112BU driver loaded that half-worked, trying this one but the device isn't getting picked up in network manager. Thanks.
MiiLink R5
ID 0bda:b812 Realtek Semiconductor Corp
https://www.amazon.com/dp/B088TNZYGG/ref=emc_b_5_t

**Comment by RinCat** [comment]
No, 0bda:b812 is the default ID for 8812bu.
Try to load manually the driver `modprobe 88x2bu`

**Comment by SherlockZeus** [comment]
That did it, thanks RinCat. I had a stupid moment... still learning. The load failed the first time because of secure boot. Loaded the module and I'm up and running.
