### ISSUE TITLE
Infinite hang after entering wifi password, but only on one specific machine.

### ISSUE THREAD

**Issue by cwestkaemper** [RinCat/RTL88x2BU-Linux-Driver#92]
I have an antenna I use on two computers with this driver. On one machine- works flawlessly across multiple partitions running different distros. On the other, it can see networks but cannot connect to them. This is not two identical antennas, this is the same antenna on two different machines. If you tell me where to get the relevant logs, I will post them.

**Comment by RinCat** [comment]
First run `dmesg` as root.

It maybe some USB control chips are not compatible, which was reported before. Try change the port.
