### ISSUE TITLE
EW-7822UAD

### ISSUE THREAD

**Issue by wkliang** [RinCat/RTL88x2BU-Linux-Driver#95]
after successful compilation and running modprobe command, there is no related device appeared.

# lsusb
7392:f822 Edimax Technology Co., Ltd Edimax AC1200 USB WiFi Adapter

// website for product
https://www.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/global/wireless_adapters_ac1200_dual-band/ew-7822uad/

**Comment by RinCat** [comment]
Fixed in https://github.com/RinCat/RTL88x2BU-Linux-Driver/commit/7391e2640d8f805b9c2aec6e0b56b9714757bb81, try update and install again.
